FROM opensuse:latest 

# sudo docker build -t opensuse/data-only .

#RUN useradd --base-dir /home/jenkins --create-home --user-group --home-dir /home/jenkins jenkins
RUN mkdir -p /var/jenkins
RUN chown -R jenkins:jenkins /var/jenkins
