#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          jenkins
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jakarta Tomcat Java Servlets and JSP server.
# Description:       # Startup script for the Jenkins Continuous Integration server
#                      (via Jakarta Tomcat Java Servlets and JSP server)



### END INIT INFO

# Set Tomcat environment.
JENKINS_USER=jenkins
LOCKFILE=/var/lock/jenkins
export HOME=/home/jenkins
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_40
export JENKINS_BASEDIR=/home/jenkins
export TOMCAT_HOME=/usr/share/tomcat7/apache-tomcat-7.0.61
export CATALINA_PID=$JENKINS_BASEDIR/jenkins-tomcat.pid
export CATALINA_OPTS="-DJENKINS_HOME=$JENKINS_BASEDIR/jenkins-home -Xmx512m -Djava.awt.headless=true"

# Source function library.
#. /etc/rc.d/init.d/functions

[ -f $TOMCAT_HOME/bin/catalina.sh ] || exit 0

case "$1" in
  start)
        # Start daemon.
        echo -n "Starting Tomcat: "
        su -p -s /bin/sh $JENKINS_USER -c "$TOMCAT_HOME/bin/catalina.sh start"
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch $LOCKFILE
        ;;
  stop)
        # Stop daemons.
        echo -n "Shutting down Tomcat: "
        su -p -s /bin/sh $JENKINS_USER -c "$TOMCAT_HOME/bin/catalina.sh stop"
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f $LOCKFILE
        ;;
  restart)
        $0 stop
        $0 start
        ;;
   status)
        status -p $CATALINA_PID -l $(basename $LOCKFILE) jenkins
        ;;
 *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
